### ISSUE TITLE
Issue with compyle

### ISSUE THREAD

**Issue by rahulhalderAERO** [pypr/pysph#286]
Hello, 

While installing pySPH in ubuntu 18.04 inside anaconda 3 using the command " pip install PySPH", I am getting an error 

ValueError: 'compyle/thrust/sort.pyx' doesn't match any files

May I know, how to fix this one.

It further shows the following command line next:

Command "/home/rahul/anaconda3/bin/python /home/rahul/anaconda3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpwsp6k4pi" failed with error code 1 in /tmp/pip-install-6ou1mlem/compyle

Rahul

**Comment by prabhuramachandran** [comment]
This is an issue with compyle and is fixed in master, I will try to push a new release in the next few days.  In the meanwhile you should be able to install using the latest version from git:
```
pip install https://github.com/pypr/compyle/zipball/master
```
the pip version of pysph is also quite old and we are working on a new release but your best bet is to use git master right now.

**Comment by rahulhalderAERO** [comment]
Thanks. I have successfully installed it now.
